# Diskritisasi Iris Dataset

In [1]:
import numpy as np
import pandas as pd

In [3]:
link="https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
data = pd.read_csv(link)
# pan.options.mode.chained_assignment = None

In [4]:
data

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

Equal Width Intervals

In [5]:
sepal_length = data[["sepal.length"]]
petal_length = data[["petal.length"]]
sepal_width = data[["sepal.width"]]
petal_width = data[["petal.width"]]

In [9]:
def cut(col, k):
  intervals = pd.cut(data[col], k).value_counts().index.to_list()
  return [[interval.left, interval.right] for interval in intervals]

In [10]:
def toCategory(list_interval, col):
  # get length interval
  length = len(list_interval)

  # sorting interval
  sort_interval = np.sort(list_interval, axis=0)

  # get category from interval
  categories = np.array([chr(65+i) for i in range(length)])[:, None]

  # Combine into interval data
  intervals = np.hstack((sort_interval, categories))

  # operate all data
  newCol = []
  for i, row in data.iterrows():
    d = row[col]
    for interval in intervals:
      if d >= interval[0].astype(float) and d <= interval[1].astype(float):
        newCol.append(interval[2])
        break

  # return new column category
  return np.array(newCol, dtype=str)

In [11]:
interval_sepal_length = cut("sepal.length", 3)
interval_petal_length = cut("petal.length", 3)
interval_sepal_width = cut("sepal.width", 3)
interval_petal_width = cut("petal.width", 3)

print("interval sepal.length = ", interval_sepal_length)
print("interval petal.length = ", interval_petal_length)
print("interval sepal.width = ", interval_sepal_width)
print("interval petal.width = ", interval_petal_width)

interval sepal.length =  [[5.5, 6.7], [4.296, 5.5], [6.7, 7.9]]
interval petal.length =  [[2.967, 4.933], [0.994, 2.967], [4.933, 6.9]]
interval sepal.width =  [[2.8, 3.6], [1.998, 2.8], [3.6, 4.4]]
interval petal.width =  [[0.9, 1.7], [0.0976, 0.9], [1.7, 2.5]]

In [12]:
sepal_length["category"] = toCategory(interval_sepal_length, "sepal.length")
petal_length["category"] = toCategory(interval_petal_length, "petal.length")
sepal_width["category"] = toCategory(interval_sepal_width, "sepal.width")
petal_width["category"] = toCategory(interval_petal_width, "petal.width")

display(sepal_length)
display(petal_length)
display(sepal_width)
display(petal_width)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

     sepal.length category
0             5.1        A
1             4.9        A
2             4.7        A
3             4.6        A
4             5.0        A
..            ...      ...
145           6.7        B
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

     petal.length category
0             1.4        A
1             1.4        A
2             1.3        A
3             1.5        A
4             1.4        A
..            ...      ...
145           5.2        C
146           5.0        C
147           5.2        C
148           5.4        C
149           5.1        C

[150 rows x 2 columns]

     sepal.width category
0            3.5        B
1            3.0        B
2            3.2        B
3            3.1        B
4            3.6        B
..           ...      ...
145          3.0        B
146          2.5        A
147          3.0        B
148          3.4        B
149          3.0        B

[150 rows x 2 columns]

     petal.width category
0            0.2        A
1            0.2        A
2            0.2        A
3            0.2        A
4            0.2        A
..           ...      ...
145          2.3        C
146          1.9        C
147          2.0        C
148          2.3        C
149          1.8        C

[150 rows x 2 columns]

Equal Frequency Intervals

In [13]:
sepal_length = data[["sepal.length"]]
petal_length = data[["petal.length"]]
sepal_width = data[["sepal.width"]]
petal_width = data[["petal.width"]]

In [14]:
def qcut(col, k):
  intervals = pd.qcut(data[col], k).value_counts().index.to_list()
  return [[interval.left, interval.right] for interval in intervals]

In [15]:
interval_sepal_length = qcut("sepal.length", 3)
interval_petal_length = qcut("petal.length", 3)
interval_sepal_width = qcut("sepal.width", 3)
interval_petal_width = qcut("petal.width", 3)

print("interval sepal.length = ", interval_sepal_length)
print("interval petal.length = ", interval_petal_length)
print("interval sepal.width = ", interval_sepal_width)
print("interval petal.width = ", interval_petal_width)

interval sepal.length =  [[5.4, 6.3], [4.2989999999999995, 5.4], [6.3, 7.9]]
interval petal.length =  [[2.633, 4.9], [0.999, 2.633], [4.9, 6.9]]
interval sepal.width =  [[1.999, 2.9], [2.9, 3.2], [3.2, 4.4]]
interval petal.width =  [[0.867, 1.6], [0.099, 0.867], [1.6, 2.5]]

In [16]:
sepal_length["category"] = toCategory(interval_sepal_length, "sepal.length")
petal_length["category"] = toCategory(interval_petal_length, "petal.length")
sepal_width["category"] = toCategory(interval_sepal_width, "sepal.width")
petal_width["category"] = toCategory(interval_petal_width, "petal.width")

display(sepal_length)
display(petal_length)
display(sepal_width)
display(petal_width)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

     sepal.length category
0             5.1        A
1             4.9        A
2             4.7        A
3             4.6        A
4             5.0        A
..            ...      ...
145           6.7        C
146           6.3        B
147           6.5        C
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

     petal.length category
0             1.4        A
1             1.4        A
2             1.3        A
3             1.5        A
4             1.4        A
..            ...      ...
145           5.2        C
146           5.0        C
147           5.2        C
148           5.4        C
149           5.1        C

[150 rows x 2 columns]

     sepal.width category
0            3.5        C
1            3.0        B
2            3.2        B
3            3.1        B
4            3.6        C
..           ...      ...
145          3.0        B
146          2.5        A
147          3.0        B
148          3.4        C
149          3.0        B

[150 rows x 2 columns]

     petal.width category
0            0.2        A
1            0.2        A
2            0.2        A
3            0.2        A
4            0.2        A
..           ...      ...
145          2.3        C
146          1.9        C
147          2.0        C
148          2.3        C
149          1.8        C

[150 rows x 2 columns]

In [17]:
sample = data[["sepal.length"]]
sample.describe()

       sepal.length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

In [18]:
np.random.seed(0)
sample["category"] = np.where(np.random.choice(2, sample.shape[0]) < 1, "A", "B")
sample

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     sepal.length category
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

In [19]:
def getOverCategory(col):
  group = sample.loc[:, :].groupby("category").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a, b, a+b)

In [20]:
def splitter(value:float, col:str)->tuple:
  # get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  # calculate into category for each data
  less_group = less.loc[:, :].groupby("category").count()
  greater_group = greater.loc[:, :].groupby("category").count()

  # get value based on category
  less_category_A = less_group.loc["A", col] 
  less_category_B = less_group.loc["B", col] 
  greater_category_A = greater_group.loc["A", col] 
  greater_category_B = greater_group.loc["B", col] 

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

In [21]:
def entropy(d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2]) 
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2]) 
  return np.sum([r1, r2]) * -1

In [22]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

In [23]:
def gain(Einitial, Enew):
  return Einitial - Enew

In [24]:
D = getOverCategory("sepal.length")
entropy_d = entropy(D)
print(D)
print(entropy_d)

(68, 82, 150)
0.993707106604508

In [25]:
split1  = splitter(4.4, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.003488151753460178

In [26]:
split2  = splitter(5.5, "sepal.length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.012302155146638905

In [27]:
split3  = splitter(7.0, "sepal.length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0005490214732508658